FROM debian:10

RUN apt-get install -y \
    build-essential=12.3 \
    git=1:2.11.0-3+deb9u7 \
    libssl-dev=1.1.0l-1~deb9u2 \
    libfcgi-dev=2.4.0-8.4+b1 \
    psmisc=22.21-2.1+b2 \
    lsb-release=9.20161125 \
    autoconf=2.69-10 